name: Docker

on:
  workflow_call:

jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build 
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:

        name: api-golang
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: vmoney2021
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.3.0
      with:
        context: .
        file: ./api-golang/Dockerfile
        push: true
        tags: vmoney2021/api-golang:${{github.ref_name}}
